package io.guestgraph.engine.api;

import java.io.IOException;
import java.io.InputStream;
import java.util.Map;
import org.springframework.core.io.ClassPathResource;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.yaml.snakeyaml.Yaml;

/**
 * Serves the complete OpenAPI document at GET /api-docs: the one file under src/main/resources/api,
 * generated by service-conventions/regen-api from the per-feature contracts under specs, which stay
 * the source of truth; the conformance test proves the served surface matches it both ways, and CI
 * holds the file against a fresh generation. Outside /api/, so no API key is required (the document
 * contains no tenant data).
 */
@RestController
public class ApiDocsController {

  private final Map<String, Object> document;

  public ApiDocsController() {
    try (InputStream in = new ClassPathResource("api/openapi.yaml").getInputStream()) {
      this.document = new Yaml().load(in);
    } catch (IOException e) {
      throw new IllegalStateException("Cannot load api/openapi.yaml", e);
    }
  }

  @GetMapping(value = "/api-docs", produces = "application/json")
  public Map<String, Object> apiDocs() {
    return document;
  }
}
